import { render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";

import App from "../App.jsx";
import PlanScreen from "./PlanScreen.jsx";
import { ApiError } from "../api.js";
import { DEMO_REQUEST } from "../plan/demoLoad.js";
import { EMPTY_PLAN, PLAN_FIXTURE } from "../plan/planFixture.js";

/* No network. `PLAN_FIXTURE` is a real `POST /plan` response generated by the solver from the
   eleven boxes of `src/demo.py`, so these tests render what the server actually returns rather than
   what a hand-written example assumes it returns. */

function show(loadPlan, request = DEMO_REQUEST) {
  return render(
    <MemoryRouter>
      <PlanScreen loadPlan={loadPlan} request={request} />
    </MemoryRouter>,
  );
}

const resolves = (plan) => vi.fn().mockResolvedValue(plan);

describe("the plan the solver returned", () => {
  it("renders every placed box", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getAllByTestId("placed-box")).toHaveLength(PLAN_FIXTURE.placements.length),
    );
    // Not just the count: each id the server sent is on the screen.
    for (const placement of PLAN_FIXTURE.placements) {
      expect(screen.getByText(placement.id)).toBeInTheDocument();
    }
  });

  it("counts them against what was asked for", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getByTestId("placed-count")).toHaveTextContent(
        `${PLAN_FIXTURE.placements.length} / ${DEMO_REQUEST.boxes.length}`,
      ),
    );
  });

  it("shows where each box sits", async () => {
    show(resolves(PLAN_FIXTURE));
    const first = PLAN_FIXTURE.placements[0];
    await waitFor(() =>
      expect(screen.getByText(`at ${first.x}, ${first.y}, ${first.z}`)).toBeInTheDocument(),
    );
  });

  it("reports the fill rate and the weight", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getByText(`${Math.round(PLAN_FIXTURE.fill_rate * 100)}%`)).toBeInTheDocument(),
    );
    expect(screen.getByText(`${Math.round(PLAN_FIXTURE.total_weight)} kg`)).toBeInTheDocument();
  });
});

describe("boxes that did not fit", () => {
  it("lists every one of them", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getAllByTestId("unplaced-box")).toHaveLength(PLAN_FIXTURE.unplaced.length),
    );
    for (const id of PLAN_FIXTURE.unplaced) {
      expect(screen.getByText(id)).toBeInTheDocument();
    }
  });

  it("is never hidden: the section is there even when everything fitted", async () => {
    const everythingFitted = { ...PLAN_FIXTURE, unplaced: [] };
    show(resolves(everythingFitted));
    await waitFor(() => expect(screen.getByTestId("all-placed")).toBeInTheDocument());
    expect(screen.getByRole("heading", { name: "Not placed" })).toBeInTheDocument();
  });

  it("says so rather than showing an empty list", async () => {
    show(resolves({ ...PLAN_FIXTURE, unplaced: [] }));
    await waitFor(() => expect(screen.getByText("Everything fitted.")).toBeInTheDocument());
    expect(screen.queryAllByTestId("unplaced-box")).toHaveLength(0);
  });
});

describe("an empty plan", () => {
  it("says no box was placed instead of showing nothing", async () => {
    show(resolves(EMPTY_PLAN), { container: DEMO_REQUEST.container, boxes: [] });
    await waitFor(() => expect(screen.getByText("No box was placed.")).toBeInTheDocument());
  });

  it("still shows the summary and the unplaced section", async () => {
    show(resolves(EMPTY_PLAN), { container: DEMO_REQUEST.container, boxes: [] });
    await waitFor(() => expect(screen.getByTestId("placed-count")).toHaveTextContent("0 / 0"));
    expect(screen.getByRole("heading", { name: "Not placed" })).toBeInTheDocument();
  });
});

describe("when the solver cannot be reached", () => {
  it("says so, and how to start it", async () => {
    const down = vi.fn().mockRejectedValue(
      new ApiError("unreachable", "Could not reach the solver at http://127.0.0.1:8000."),
    );
    show(down);
    await waitFor(() => expect(screen.getByRole("alert")).toBeInTheDocument());
    expect(screen.getByText(/Could not reach the solver/)).toBeInTheDocument();
    expect(screen.getByText(/uvicorn server:app/)).toBeInTheDocument();
  });

  it("shows the reason when the solver refused the load", async () => {
    const refused = vi.fn().mockRejectedValue(
      new ApiError("refused", "duplicate box ids: carton-1", "duplicate box ids: carton-1"),
    );
    show(refused);
    await waitFor(() =>
      expect(screen.getByText(/duplicate box ids: carton-1/)).toBeInTheDocument(),
    );
  });

  it("never shows a plan it does not have", async () => {
    show(vi.fn().mockRejectedValue(new ApiError("server", "The solver answered 500.")));
    await waitFor(() => expect(screen.getByRole("alert")).toBeInTheDocument());
    expect(screen.queryAllByTestId("placed-box")).toHaveLength(0);
    expect(screen.queryByTestId("placed-count")).not.toBeInTheDocument();
  });
});

describe("the route", () => {
  it("is reachable at /app/plan", () => {
    render(
      <MemoryRouter initialEntries={["/app/plan"]}>
        <App />
      </MemoryRouter>,
    );
    expect(screen.getByRole("heading", { level: 1, name: "Load plan" })).toBeInTheDocument();
  });
});
