import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";

/* WebGL does not exist in jsdom, so the scene renders as plain elements here. The 3D view has its
   own tests in plan/scene.test.jsx, which check the parts that are arithmetic rather than pixels —
   what a canvas actually draws is not something this suite can see, and pretending otherwise would
   be a test that cannot fail. */
vi.mock("@react-three/fiber", () => ({
  Canvas: ({ children, ...rest }) => <div data-testid="scene" {...rest}>{children}</div>,
  // `useThree` reaches the renderer's camera, which the camera presets move (`SA-23`). There is no
  // renderer here, so it hands back a camera-shaped object: the preset's effect runs without throwing
  // and the rest of the screen stays testable. What the camera *sees* is not something jsdom can tell
  // us either way — `plan/scene.test.jsx` asserts the view positions directly instead.
  useThree: (selector) => {
    const camera = { position: { set: () => {} }, lookAt: () => {} };
    return selector ? selector({ camera }) : { camera };
  },
}));
vi.mock("@react-three/drei", () => ({ OrbitControls: () => null, Edges: () => null }));

import App from "../App.jsx";
import PlanScreen from "./PlanScreen.jsx";
import { ApiError } from "../api.js";
import { DEMO_REQUEST } from "../plan/demoLoad.js";
import { EMPTY_PLAN, PLAN_FIXTURE } from "../plan/planFixture.js";

/* No network. `PLAN_FIXTURE` is a real `POST /plan` response generated by the solver from the
   eleven boxes of `src/demo.py`, so these tests render what the server actually returns rather than
   what a hand-written example assumes it returns. */

function show(loadPlan, request = DEMO_REQUEST) {
  return render(
    <MemoryRouter>
      <PlanScreen loadPlan={loadPlan} request={request} />
    </MemoryRouter>,
  );
}

const resolves = (plan) => vi.fn().mockResolvedValue(plan);

describe("the plan the solver returned", () => {
  it("renders every placed box", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getAllByTestId("placed-box")).toHaveLength(PLAN_FIXTURE.placements.length),
    );
    // Not just the count: each id the server sent is in the list. Scoped to the list because the
    // next box's id also appears in the "Next box" card above it (`SA-23`), so a bare text query
    // would now find two of one id and none of the rest.
    //
    // The id cell is compared whole rather than searched for inside the row's text: a substring
    // match would pass for a partial id, so `b1` would satisfy an assertion about `b12`.
    const listedIds = screen.getAllByTestId("placed-box")
      .map((row) => row.querySelector(".plan-id").textContent);
    for (const placement of PLAN_FIXTURE.placements) {
      expect(listedIds).toContain(placement.id);
    }
  });

  it("counts them against what was asked for", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getByTestId("placed-count")).toHaveTextContent(
        `${PLAN_FIXTURE.placements.length} / ${DEMO_REQUEST.boxes.length}`,
      ),
    );
  });

  it("shows where each box sits", async () => {
    show(resolves(PLAN_FIXTURE));
    const first = PLAN_FIXTURE.placements[0];
    await waitFor(() =>
      expect(screen.getByText(`at ${first.x}, ${first.y}, ${first.z}`)).toBeInTheDocument(),
    );
  });

  it("reports the fill rate and the weight", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getByText(`${Math.round(PLAN_FIXTURE.fill_rate * 100)}%`)).toBeInTheDocument(),
    );
    expect(screen.getByText(`${Math.round(PLAN_FIXTURE.total_weight)} kg`)).toBeInTheDocument();
  });
});

describe("the 3D view", () => {
  it("is on the screen once there is a plan", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() => expect(screen.getByTestId("scene")).toBeInTheDocument());
  });

  it("is not shown when there is no plan to draw", async () => {
    show(vi.fn().mockRejectedValue(new ApiError("unreachable", "no solver")));
    await waitFor(() => expect(screen.getByRole("alert")).toBeInTheDocument());
    expect(screen.queryByTestId("scene")).not.toBeInTheDocument();
  });

  it("says what to do before a box is chosen", async () => {
    show(resolves(PLAN_FIXTURE));
    const hint = "Tap a box to see what it is.";
    await waitFor(() => expect(screen.getByText(hint)).toBeInTheDocument());
    expect(screen.queryByTestId("inspector")).not.toBeInTheDocument();
  });

  it("shows the box that was tapped", async () => {
    const user = userEvent.setup();
    show(resolves(PLAN_FIXTURE));
    await waitFor(() => expect(screen.getAllByTestId("placed-box")).not.toHaveLength(0));
    const first = PLAN_FIXTURE.placements[0];
    await user.click(screen.getAllByTestId("placed-box")[0]);
    const inspector = screen.getByTestId("inspector");
    expect(inspector).toHaveTextContent(first.id);
    expect(inspector).toHaveTextContent(`${first.dx} × ${first.dy} × ${first.dz} cm`);
  });
});

describe("boxes that did not fit", () => {
  it("lists every one of them", async () => {
    show(resolves(PLAN_FIXTURE));
    await waitFor(() =>
      expect(screen.getAllByTestId("unplaced-box")).toHaveLength(PLAN_FIXTURE.unplaced.length),
    );
    for (const id of PLAN_FIXTURE.unplaced) {
      expect(screen.getByText(id)).toBeInTheDocument();
    }
  });

  it("is never hidden: the section is there even when everything fitted", async () => {
    const everythingFitted = { ...PLAN_FIXTURE, unplaced: [] };
    show(resolves(everythingFitted));
    await waitFor(() => expect(screen.getByTestId("all-placed")).toBeInTheDocument());
    expect(screen.getByRole("heading", { name: "Not placed" })).toBeInTheDocument();
  });

  it("says so rather than showing an empty list", async () => {
    show(resolves({ ...PLAN_FIXTURE, unplaced: [] }));
    await waitFor(() => expect(screen.getByText("Everything fitted.")).toBeInTheDocument());
    expect(screen.queryAllByTestId("unplaced-box")).toHaveLength(0);
  });
});

describe("an empty plan", () => {
  it("says no box was placed instead of showing nothing", async () => {
    show(resolves(EMPTY_PLAN), { container: DEMO_REQUEST.container, boxes: [] });
    await waitFor(() => expect(screen.getByText("No box was placed.")).toBeInTheDocument());
  });

  it("still shows the summary and the unplaced section", async () => {
    show(resolves(EMPTY_PLAN), { container: DEMO_REQUEST.container, boxes: [] });
    await waitFor(() => expect(screen.getByTestId("placed-count")).toHaveTextContent("0 / 0"));
    expect(screen.getByRole("heading", { name: "Not placed" })).toBeInTheDocument();
  });
});

describe("when the solver cannot be reached", () => {
  it("says so, and how to start it", async () => {
    const down = vi.fn().mockRejectedValue(
      new ApiError("unreachable", "Could not reach the solver at http://127.0.0.1:8000."),
    );
    show(down);
    await waitFor(() => expect(screen.getByRole("alert")).toBeInTheDocument());
    expect(screen.getByText(/Could not reach the solver/)).toBeInTheDocument();
    expect(screen.getByText(/uvicorn server:app/)).toBeInTheDocument();
  });

  it("shows the reason when the solver refused the load", async () => {
    const refused = vi.fn().mockRejectedValue(
      new ApiError("refused", "duplicate box ids: carton-1", "duplicate box ids: carton-1"),
    );
    show(refused);
    await waitFor(() =>
      expect(screen.getByText(/duplicate box ids: carton-1/)).toBeInTheDocument(),
    );
  });

  it("never shows a plan it does not have", async () => {
    show(vi.fn().mockRejectedValue(new ApiError("server", "The solver answered 500.")));
    await waitFor(() => expect(screen.getByRole("alert")).toBeInTheDocument());
    expect(screen.queryAllByTestId("placed-box")).toHaveLength(0);
    expect(screen.queryByTestId("placed-count")).not.toBeInTheDocument();
  });
});

describe("the route", () => {
  it("is reachable at /app/plan", () => {
    render(
      <MemoryRouter initialEntries={["/app/plan"]}>
        <App />
      </MemoryRouter>,
    );
    expect(screen.getByRole("heading", { level: 1, name: "Load plan" })).toBeInTheDocument();
  });
});

describe("the dressing from the mockup (SA-23)", () => {
  // A plan with everything placed and nothing unapplied, so the green state is reachable.
  const CLEAN = {
    placements: [
      { id: "a", x: 0, y: 0, z: 0, dx: 60, dy: 40, dz: 40 },
      { id: "b", x: 60, y: 0, z: 0, dx: 50, dy: 40, dz: 40 },
    ],
    unplaced: [],
    fill_rate: 0.5,
    total_weight: 30,
    not_applied: [],
  };
  const REQUEST = {
    container: { length: 200, width: 100, height: 100, max_weight: 500 },
    boxes: [{ id: "a", length: 60, width: 40, height: 40, weight: 12 },
            { id: "b", length: 50, width: 40, height: 40, weight: 18 }],
  };

  function showPlan(plan) {
    return render(
      <MemoryRouter>
        <PlanScreen loadPlan={() => Promise.resolve(plan)} request={REQUEST} />
      </MemoryRouter>,
    );
  }

  it("offers the delivery order as a link rather than restructuring the navigation", async () => {
    showPlan(CLEAN);
    await screen.findByTestId("loaded-count");
    expect(screen.getByRole("link", { name: "Delivery order" }))
      .toHaveAttribute("href", "/app/route");
  });

  it("names the next box from the plan, with its real size and weight", async () => {
    showPlan(CLEAN);
    const card = await screen.findByRole("complementary", { name: "Next box" });
    expect(card).toHaveTextContent("a");
    expect(card).toHaveTextContent("60 × 40 × 40 cm");
    expect(card).toHaveTextContent("12 kg");
  });

  it("invents no storage reference and no size bucket", async () => {
    // The mockup reads "Stop 3 · A-12 / Medium · 8 kg". We have no slot reference and no size
    // buckets, so neither appears — the same rule that kept the doors off the route screen.
    showPlan(CLEAN);
    const card = await screen.findByRole("complementary", { name: "Next box" });
    expect(card).not.toHaveTextContent(/A-\d+/);
    expect(card).not.toHaveTextContent(/medium|small|large/i);
  });

  it("advances through the loading order when the operator says loaded", async () => {
    showPlan(CLEAN);
    expect(await screen.findByTestId("loaded-count")).toHaveTextContent("0 / 2 loaded");
    const next = screen.getByRole("button", { name: /loaded, next/i });
    fireEvent.click(next);
    expect(screen.getByTestId("loaded-count")).toHaveTextContent("1 / 2 loaded");
    // And the card moves on to the box that is genuinely next in the solver's order.
    expect(screen.getByRole("complementary", { name: "Next box" })).toHaveTextContent("b");
  });

  it("stops at the end rather than looping round", async () => {
    showPlan(CLEAN);
    await screen.findByTestId("loaded-count");
    const next = screen.getByRole("button", { name: /loaded, next/i });
    fireEvent.click(next);
    fireEvent.click(next);
    expect(screen.getByTestId("loaded-count")).toHaveTextContent("2 / 2 loaded");
    expect(next).toBeDisabled();
    expect(screen.getByRole("complementary", { name: "Next box" })).toHaveTextContent(/all loaded/i);
  });

  it("shows the green state only when the plan really is complete", async () => {
    showPlan(CLEAN);
    expect(await screen.findByTestId("plan-state")).toHaveTextContent(/all items placed/i);
  });

  it("refuses the green tick when a box could not be placed", async () => {
    // The lie this project exists to refuse: a tick over an incomplete plan.
    showPlan({ ...CLEAN, unplaced: ["c"] });
    const state = await screen.findByTestId("plan-state");
    expect(state).not.toHaveTextContent(/all items placed/i);
    expect(state).toHaveTextContent("1 not placed");
  });

  it("refuses it when a rule went unapplied, even with everything placed", async () => {
    showPlan({ ...CLEAN, not_applied: [{ type: "at_bottom", item: "a", reason: "issue #29" }] });
    const state = await screen.findByTestId("plan-state");
    expect(state).not.toHaveTextContent(/all items placed/i);
    expect(state).toHaveTextContent("1 rule not applied");
  });

  it("counts the plan in hand, not the mockup's 124", async () => {
    showPlan(CLEAN);
    expect(await screen.findByTestId("loaded-count")).toHaveTextContent("/ 2 loaded");
  });

  it("offers the four camera views, each a large enough target to press in gloves", async () => {
    showPlan(CLEAN);
    await screen.findByTestId("loaded-count");
    for (const name of ["3D", "Top", "Left", "Right"]) {
      expect(screen.getByRole("button", { name })).toBeInTheDocument();
    }
    expect(screen.getByRole("button", { name: "3D" })).toHaveAttribute("aria-pressed", "true");
    fireEvent.click(screen.getByRole("button", { name: "Top" }));
    expect(screen.getByRole("button", { name: "Top" })).toHaveAttribute("aria-pressed", "true");
    expect(screen.getByRole("button", { name: "3D" })).toHaveAttribute("aria-pressed", "false");
  });
});

describe("names rather than internal ids (SA-24)", () => {
  // Real manifest ids, so the label and stop lookups resolve the way they do in the demo. The point
  // of the task: `B16` and `S7` were what the screen put in front of whoever was watching it.
  const NAMED = {
    placements: [{ id: "B16", x: 0, y: 0, z: 0, dx: 40, dy: 85, dz: 45 }],
    unplaced: [], fill_rate: 0.1, total_weight: 62, not_applied: [],
  };
  const REQ = {
    container: { length: 300, width: 170, height: 170, max_weight: 1200 },
    boxes: [{ id: "B16", length: 40, width: 85, height: 45, weight: 62 }],
  };

  function showNamed() {
    return render(
      <MemoryRouter>
        <PlanScreen loadPlan={() => Promise.resolve(NAMED)} request={REQ} />
      </MemoryRouter>,
    );
  }

  it("leads with the box's name in the list", async () => {
    showNamed();
    await screen.findByTestId("loaded-count");
    const row = screen.getByTestId("placed-box");
    expect(row).toHaveTextContent("crate, tiles");
  });

  it("keeps the id, as technical detail rather than the label", async () => {
    // Still there — it is what is printed on the box and what a test reads to say which row this is —
    // but no longer the thing an operator is asked to recognise.
    showNamed();
    await screen.findByTestId("loaded-count");
    const id = screen.getByTestId("placed-box").querySelector(".plan-id");
    expect(id).toHaveTextContent("B16");
    expect(id.className).toMatch(/plan-id--aside/);
  });

  it("names the stop on the next-box card instead of its id", async () => {
    showNamed();
    const card = await screen.findByRole("complementary", { name: "Next box" });
    expect(card).toHaveTextContent("Saint-Germain");   // B16's stop is S7
    expect(card).not.toHaveTextContent(/\bS7\b/);
  });

  it("falls back to the id when the manifest has never heard of the box", async () => {
    // The eleven-box demo load. An id is a poor label, but inventing a name for a box we know nothing
    // about would be worse, and the id cell has to stay present either way.
    render(
      <MemoryRouter>
        <PlanScreen
          loadPlan={() => Promise.resolve({ ...NAMED,
            placements: [{ id: "sofa", x: 0, y: 0, z: 0, dx: 200, dy: 90, dz: 80 }] })}
          request={{ ...REQ, boxes: [{ id: "sofa", length: 200, width: 90, height: 80, weight: 45 }] }}
        />
      </MemoryRouter>,
    );
    await screen.findByTestId("loaded-count");
    const id = screen.getByTestId("placed-box").querySelector(".plan-id");
    expect(id).toHaveTextContent("sofa");
    expect(id.className).not.toMatch(/plan-id--aside/);
  });
});

/* `LP-22`: a tap is a question about a box, never an instruction about the plan. The loading order
   is the solver's, and `Loaded, next` is the only thing that moves through it — these hold that
   line, because an interface that let a tap rewrite the plan would contradict the whole project. */
describe("consulting a box (LP-22)", () => {
  const PLAN = {
    placements: [
      { id: "a", x: 0, y: 0, z: 0, dx: 60, dy: 40, dz: 40 },
      { id: "b", x: 60, y: 0, z: 0, dx: 50, dy: 40, dz: 40 },
      { id: "c", x: 110, y: 0, z: 0, dx: 40, dy: 40, dz: 40 },
    ],
    unplaced: [],
    fill_rate: 0.5,
    total_weight: 40,
    not_applied: [],
  };
  const REQUEST = {
    container: { length: 200, width: 100, height: 100, max_weight: 500 },
    boxes: [
      { id: "a", length: 60, width: 40, height: 40, weight: 12 },
      { id: "b", length: 50, width: 40, height: 40, weight: 18 },
      { id: "c", length: 40, width: 40, height: 40, weight: 10 },
    ],
  };

  const showPlan = () =>
    render(
      <MemoryRouter>
        <PlanScreen loadPlan={() => Promise.resolve(PLAN)} request={REQUEST} />
      </MemoryRouter>,
    );

  const nextCard = () => screen.getByRole("complementary", { name: "Next box" });

  it("leaves the next box exactly as it was when another box is tapped", async () => {
    const user = userEvent.setup();
    showPlan();
    await screen.findByTestId("loaded-count");
    const before = nextCard().textContent;
    await user.click(screen.getAllByTestId("placed-box")[2]);
    expect(screen.getByTestId("inspector")).toHaveTextContent("c");
    expect(nextCard().textContent).toBe(before);
  });

  it("advances from the solver's order, not from what was tapped", async () => {
    const user = userEvent.setup();
    showPlan();
    await screen.findByTestId("loaded-count");
    await user.click(screen.getAllByTestId("placed-box")[2]);
    await user.click(screen.getByRole("button", { name: /loaded, next/i }));
    // `b` follows `a`. Had the tap reassigned, the order would have jumped to `c`.
    expect(nextCard()).toHaveTextContent("b");
  });

  it("says so in words before anything has been tapped", async () => {
    showPlan();
    await screen.findByTestId("loaded-count");
    expect(screen.getByText("It does not change what goes in next.")).toBeInTheDocument();
  });

  it("puts the card away without touching the plan", async () => {
    const user = userEvent.setup();
    showPlan();
    await screen.findByTestId("loaded-count");
    const before = nextCard().textContent;
    await user.click(screen.getAllByTestId("placed-box")[1]);
    await user.click(screen.getByRole("button", { name: "Done" }));
    expect(screen.queryByTestId("inspector")).not.toBeInTheDocument();
    expect(nextCard().textContent).toBe(before);
  });
});
